#
# This is kibot configuration.
#
# Edit this file to generate more stuff automatically.
#

kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: true
  ignore_unconnected: false

filters:
  - name: lcsc_parts
    type: generic
    include_only:
      - column: 'lcsc#'
        regex: '^C\d+'

outputs:
  - name: print_sch
    type: pdf_sch_print
    options:
      output: 'schematics.pdf'


  - name: pcb_print
    type: pcb_print
    options:
      output: 'pcb_%p.pdf'
      force_edge_cuts: true
      keep_temporal_files: false
      plot_sheet_reference: false
      color_theme: '_builtin_default'
      pages:
        - sheet: 'Drawings'
          scaling: 2
          layers: 
          - layer: F.Mask
            color: '#111111'
          - layer: F.SilkS
            color: '#FFFFFF'
          - layer: User.Drawings
            color: '#444444'


  - name: merge_pcb_pdf
    type: pdfunite
    run_by_default: false
    options:
      output: 'pcb.pdf'
      outputs:
        - source: 'pcb_pwr.pdf'
        - source: 'pcb_pwr.pdf'


  - name: pcb_img_3d_main
    type: render_3d
    options:
      output: 'img_pcb_3d_main_%p.png'
      download: true
      rotate_x: 0
      rotate_z: 9
      move_x: 0
      move_y: 0
      solder_mask: '#104020'
      orthographic: false
      ray_tracing: true
      width: 700
      height: 700
      view: top
      zoom: 4
  - name: pcb_img_3d_main_back
    type: render_3d
    options:
      output: 'img_pcb_3d_main_back_%p.png'
      download: true
      rotate_x: 0
      rotate_z: 9
      move_x: 0
      move_y: 0
      solder_mask: '#104020'
      orthographic: false
      ray_tracing: true
      width: 500
      height: 500
      view: bottom
      zoom: 4


  - name: ibom
    type: ibom
    run_by_default: false
    options:
      output: 'ibom.html'
      no_compression: true
      highlight_pin1: true
      layer_view: F


  - name: lcsl_bom
    type: bom
    options:
      output: 'bom_lcsc.csv'
      ref_separator: ','
      exclude_filter: lcsc_parts
      columns:
        - field: 'Quantity Per PCB'
          name: 'Quantity'
        - field: 'lcsc#'
          name: 'LCSC Part Number'
        - 'Value'
        - 'Footprint'
      group_fields: ['lcsc#']
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true


  - name: full_bom
    type: bom
    options:
      output: 'bom.csv'
      ref_separator: ','
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true


  #
  # JLC production stuff below
  #
  - name: fab_gerbers
    type: gerber
    run_by_default: false
    options: &gerber_options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: false
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
    layers:
      - F.Cu
      - B.Cu
      - Edge.Cuts
      - F.SilkS
      - F.Mask
      - F.Paste
      - B.SilkS
      - B.Mask
      - B.Paste

  - name: fab_drill
    type: excellon
    run_by_default: false
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      output: "%f%i.%x"

  - name: fab_netlist
    type: netlist
    run_by_default: false
    options:
      format: ipc
      output: 'netlist.ipc'

  - name: fab_position
    type: position
    run_by_default: false
    options:
      format: CSV
      output: '_pos.csv'
      only_smd: false
      separate_files_for_front_and_back: false
      right_digits: 3
      pre_transform: _rot_footprint
      columns:
        - id: Ref
          name: 'Designator'
        - id: PosX
          name: 'Mid X'
        - id: PosY
          name: 'Mid Y'
        - id: Side
          name: 'Layer'
        - id: Rot
          name: 'Rotation'


